### ISSUE TITLE
请问这个现在还能用吗，运行报错了不知是什么原因

### ISSUE THREAD

**Issue by Paubrk** [evilinsipid/QQ-Group-Check-in#2]
`# python qq.py
Traceback (most recent call last):
  File "qq.py", line 110, in <module>
    main()
  File "qq.py", line 78, in main
    skey = s.cookies['skey']
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='skey', domain=None, path=None"

**Comment by xyang532** [comment]
很抱歉呀，没设置邮箱提醒所以都没看到这个issue。这个项目现在还是可以使用的，你的报错可能是环境的问题，你是在Windows还是linux上使用的

**Comment by linking123** [comment]
同报这个错。。换一个qq账号就不行了

第一个号是本地常用号码，第二个是朋友的异地号码。

估计是腾讯的限制。
